GET http://localhost:3000/api/blogPosts


###
POST http://localhost:3000/api/blogPost
Content-Type: application/json

{
    "name": "ZazA",
    "content": "Hejsan"
}

###
PUT http://localhost:3000/api/blogPost/66018bc721b89632f5b3a891
Content-Type: application/json

{
    "title": "Zamiel",
    "content": "Buaka"
}


###
DELETE http://localhost:3000/api/blogPost/660068d83992d537ccea3356